#! /opt/local/bin/bash
#-x means print commands as they are executed
#get tree view of MRtoolbox directory and write it to the README.md file

if ! command -v tree &> /dev/null
then
    echo "command 'tree' not found... install it."

    exit 1
fi

echo -e '# MRToolbox \n\n A growing collection of Max tools... \n\n ```' > ../README.md

tree ../ >> ../README.md

echo '```' >> ../README.md


echo -e '\n\n\nThis is a constant work in progress... so things might change and/or break at any point...' >> ../README.md